version: "3.8"

services:
  app:
    # IMPORTANTE: Substitua 'SEU-USUARIO/SEU-REPO'
    # Esta é a imagem que o nosso CI publica no GHCR
    image: ghcr.io/raffael-carvalho/ci-cd-sec:latest
    ports:
      - "3000:3000" # Mapeia a porta do contêiner para localhost:3000
    restart: always
    pull_policy: always # Sempre tenta baixar a imagem mais nova
